# Automatically generated by configure - do not modify
SRC_PATH=/home/zhangxiang/workspace/paper/optee/qemu/roms/seabios
AS=as
CCAS=/usr/bin/ccache gcc
CC=/usr/bin/ccache gcc
BCC=bcc
CPP=/usr/bin/ccache gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
